name: ðŸ”„ Regression Tests
on:
  push:
    branches: [main]

jobs:
  call-tests:
    uses: ./.github/workflows/_test_logic.yml
    with:
      env: www
      browser: chromium
      marker: regression
    secrets: inherit